### ISSUE TITLE
libgtk-1.2.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Amaikokonut** [Nazushvel/dstation-2020#9]
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
Just tried this out on my nearly-fresh Debian Buster install, following the directions, generally having no idea what I'm doing.

(as a minor note, while following the Pre-run steps, `sudo dpkg --add-arch i386` didn't work for me `(dpkg: error: unknown option --add-arch) `but `sudo dpkg --add-architecture i386` did.)

The install seemed to run fine, but trying to start it gives me `./lc2e: error while loading shared libraries: libgtk-1.2.so.0: cannot open shared object file: No such file or directory`

It looks like maybe it had some trouble with the gtk lib in the install, everything looked good up until:
```
Archives: 3
OK archives: 3
Files: 3
Size:       3179556
Compressed: 1204393
zstd: can't stat gtk+-1.2.10-70.el6.i686.cpio.zstd : No such file or directory -- ignored 
glib-1.2.10-58.fc32.i686.cpio.zstd: 418796 bytes                               
usr/doc/SDL-1.2.9
usr/doc/SDL-1.2.9/BUGS
usr/doc/SDL-1.2.9/COPYING
usr/doc/SDL-1.2.9/CREDITS
usr/doc/SDL-1.2.9/README-SDL.txt
usr/lib/libSDL-1.1.so.0
usr/lib/libSDL-1.2.so.0
usr/lib/libSDL-1.2.so.0.7.2
993 blocks
./dstation-2020: line 78: gtk.cpio: No such file or directory
```

Full install log attached: [ds-install-log.txt](https://github.com/Nazushvel/dstation-2020/files/5042102/ds-install-log.txt)

Did I miss anything?

**Comment by Amaikokonut** [comment]
In case it's worth mentioning, the game DID run fine (minus sound) after I grabbed old versions of libgtk and libgdk from previous installs and dropped them in the dstation folder.

**Comment by digitalcheetah** [comment]
Okay. I think I know what's going on. The script seems to be tripping up on GTK+, since it's not what it's expecting.

I have an idea that might work: https://github.com/digitalcheetah/dstation-2020/blob/gtk%2B-fix/dstation-2020

Try replacing the dstation-2020 script with this one.

**Comment by Nazushvel** [comment]
fix pushed to repro @Amaikokonut  when you have time please let me know if this new push has fixed your issue. Also if you are on the creatures discord you can message me there if it needs further troubleshooting username "BloodLines"

**Comment by Amaikokonut** [comment]
Seems to work perfectly now! Thanks.
